version: '3.6'

services:
  app-nginx:
    image: nginx:latest
    container_name: app-nginx
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - "/etc/letsencrypt/:/etc/letsencrypt/"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend

networks:
  backend:
    name: backend
    external: true